#!/bin/busybox ash
set -x

echo "Reached Target: Kernel Init"

# Setup basic environment
export PATH="/bin"
export LD_LIBRARY_PATH="/lib"
export LD_LIBRARY_PATH_64="/lib"

# Mount essentials
/bin/busybox mount -t proc proc /proc -o nosuid,noexec,nodev
/bin/busybox mount -t sysfs sys /sys -o nosuid,noexec,nodev
/bin/busybox mount -t devtmpfs dev /dev -o nosuid,mode=0700
/bin/busybox mount -t tmpfs run /run -o nosuid,nodev,mode=0700
if [ -e /sys/firmware/efi ]; then
    /bin/busybox mount -t efivarfs efivarfs /sys/firmware/efi/efivars -o nosuid,noexec,nodev
fi
if [ -e /proc/kcore ]; then
    ln -sfT /proc/kcore /dev/core
fi

# Bind self to stdin stdout and stderr
ln -sfT /proc/self/fd /dev/fd
ln -sfT /proc/self/fd/0 /dev/stdin
ln -sfT /proc/self/fd/1 /dev/stdout
ln -sfT /proc/self/fd/2 /dev/stderr

# Audio hotfix
mkdir -p /dev/snd
mknod /dev/snd/controlC0 c 116 0
mknod /dev/snd/hwC0D0 c 116 32
mknod /dev/snd/pcmC0D0c c 116 24
mknod /dev/snd/timer c 116 33

# Load essential modules for input
/bin/modprobe usbhid
/bin/modprobe hid_generic
/bin/modprobe serio
/bin/modprobe atkbd
/bin/modprobe serio_raw
/bin/modprobe i8042

# Load essential modules for sound
/bin/modprobe snd
/bin/modprobe snd_pcm
/bin/modprobe snd_timer
/bin/modprobe snd_hwdep
/bin/modprobe snd_hda_intel
/bin/modprobe snd_usb_audio
/bin/modprobe snd_hda_codec
/bin/modprobe snd_hda_codec_realtek
/bin/modprobe snd_ens1371
/bin/modprobe snd_ac97_codec

mdev -s

echo "Reached Target: Init Complete"

# Launch shell for user
ash 0</dev/stdin 1>/dev/stdout 2>/dev/stderr

# Gracefully exit without kernel panic
echo 1 > /proc/sys/kernel/sysrq 
echo s > /proc/sysrq-trigger
echo u > /proc/sysrq-trigger
echo o > /proc/sysrq-trigger
while true; do
    sleep 60
done
